# Generated by Django 3.2 on 2022-01-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_remove_todo_date_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
